# Generated by Django 4.0.4 on 2022-05-30 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriteLevelOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorites_level_one', to='essi_stock.categorite')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriteLevelTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categorite_level_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorites_level_two', to='essi_stock.categoritelevelone')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=3000)),
                ('price', models.CharField(max_length=200)),
                ('categorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorites', to='essi_stock.categorite')),
                ('categorite_level_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorites_level_one', to='essi_stock.categoritelevelone')),
                ('categorite_level_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='essi_stock.categoriteleveltwo')),
            ],
        ),
    ]
